version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.4.0

parameters:
  suite:
    type: string
    default: Smoke
  notifyToSlack:
    type: boolean
    default: true
  ApiTrigger:
    type: boolean
    default: false
  NightlyRunNotify:
    type: boolean
    default: true

jobs:
  Running-configuration:
    parameters:
      NightlyRunNotify:
        type: boolean
        default: false

    docker:
      - image: circleci/openjdk:11.0.6-jdk-buster-node-browsers-legacy

    working_directory: ~/ui-automation-listings

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-


      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Run tests
          command: mvn
            clean verify -P parallel
          no_output_timeout: 40m

      - store_artifacts:
          name: Upload Cucumber report
          path: target/cucumber-html-reports
          destination: Report/Cucumber

      # Send notification to my Slack channel
      - when:
          condition: << pipeline.parameters.notifyToSlack >>
          steps:
            - slack/status:
                channel: C041TRUTE4V
                fail_only: false
                only_for_branches: master
                webhook: $SLACK_WEBHOOK

workflows:

  commit-workflow:
    when:
      and:
        - equal: [ false, << pipeline.parameters.ApiTrigger >>]
    jobs:
      - Running-configuration:
          filters:
            branches:
              only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 5 * * 3"
          filters:
            branches:
              only:
                - master
    jobs:
      - Running-configuration:
          NightlyRunNotify: true

  on_demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - Running-configuration
      - buid_approval:
            type: approval