version: 2.1
orbs:
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.4.0

parameters:
  suite:
    type: string
    default: Smoke
  notifyToSlack:
    type: boolean
    default: true
  ApiTrigger:
    type: boolean
    default: false
  NightlyRunNotify:
    type: boolean
    default: true


executors:
  test-executor:
    working_directory: ~/MyBDDFrame

    docker:
      - image: circleci/openjdk:11.0.6-jdk-buster-node-browsers-legacy

    environment:
      MAVEN_OPTS: -Xmx3200m

commands:
  #My custom command name 'install-browsers'
  install-browsers:
    description: "Checkout to my code and install browsers"
    steps:
      - checkout
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver

  restore-and-save-cache:
    description: "Restore and save cache"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2

          key: v1-dependencies-{{ checksum "pom.xml" }}

  running-automation-tests:
    description: "Running automation tests"
    steps:
      - run:
          name: Run tests
          command: mvn
            clean verify -P parallel
          no_output_timeout: 40m

  generating-cucumber-report:
    description: "generating-cucumber-report"
    steps:
      - store_artifacts:
          name: Upload Cucumber report
          path: target/cucumber-html-reports
          destination: Report/Cucumber

  send-notification-to-slack-channel:
    description: "Send notification to Slack channel"
    steps:
      - when:
          condition: << pipeline.parameters.notifyToSlack >>
          steps:
            - slack/status:
                channel: C041TRUTE4V
                fail_only: false
                only_for_branches: master
                webhook: $SLACK_WEBHOOK

  mvn-checkstyle:
    description: Checkstyle check code
    steps:
      - run:
          name: Checkstyle check code
          command: |
            mvn clean site
            mvn checkstyle:checkstyle
          no_output_timeout: 90m

  store-checkstyle-artifacts:
    description: Store Checkstyle generated artifacts
    steps:
      - store_artifacts:
          path: target/site
          destination: Report/Checkstyle

jobs:
  checkstyle-check:
    executor: test-executor
    steps:
      - mvn-checkstyle
      - store-checkstyle-artifacts

  #There is a custom name of my job. We can change it anytime
  automation-tests-running-configuration:
    parameters:
      NightlyRunNotify:
        type: boolean
        default: false
    executor: test-executor
    #There is all custom names which located under 'Commands' section
    steps:
      - install-browsers
      - restore-and-save-cache
      - running-automation-tests
      - generating-cucumber-report
      - send-notification-to-slack-channel


workflows:

  commit-workflow:
    when:
      and:
        - equal: [ false, << pipeline.parameters.ApiTrigger >>]
    jobs:
      - automation-tests-running-configuration:
          filters:
            branches:
              only:
                - master

  schedule-workflow:
    triggers:
      - schedule:
          cron: "0 5 * * 3"
          filters:
            branches:
              only:
                - master
    jobs:
      - automation-tests-running-configuration:
          NightlyRunNotify: true

  on-demand:
    when: << pipeline.parameters.ApiTrigger >>
    jobs:
      - checkstyle-check
      - automation-tests-running-configuration